# Generated by Django 2.0.1 on 2018-03-09 06:21

import apps.album.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.album.models.image_directory_path)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='AlbumFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('cover', models.ImageField(upload_to=apps.album.models.cover_directory_path)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.AlbumFile'),
        ),
    ]
