# Generated by Django 2.0.2 on 2018-03-17 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=500)),
                ('is_active', models.IntegerField()),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('lastUpdate',),
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rewardCount', models.IntegerField()),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('actionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.Activity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('lastUpdate',),
            },
        ),
        migrations.CreateModel(
            name='RewardRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reward', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
    ]
