# Generated by Django 2.0.2 on 2018-03-17 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=500)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('objectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.Activity')),
            ],
            options={
                'ordering': ('lastUpdate',),
            },
        ),
        migrations.AddField(
            model_name='rewardrecord',
            name='rewardId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reward.Reward'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rewardrecord',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.ActivityObject'),
        ),
    ]
