# Generated by Django 2.0.2 on 2018-03-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_auto_20180317_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityobject',
            name='unit',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
