# Generated by Django 2.0.2 on 2018-03-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0003_activityobject_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityobject',
            name='probably',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
